info:
  name: @project.artifactId@
  version: @project.version@
  origin: @scm.url@
  commit: @buildNumber@
  branch: @scmBranch@
  built: @timestamp@

server:
  port: 9091

project:
  basedir: ${basedir}

spring.http.multipart:
  max-file-size: 12800MB
  max-request-size: 12800MB

spring.datasource:
  url: jdbc:postgresql://localhost/postgres?currentSchema=gateway
  driver-class-name: org.postgresql.Driver
  continue-on-error: true
  schema: classpath:/schema.sql
  username: postgres
  password: postgres

management.endpoint.health.show-details: always
endpoints.health.sensitive: false
management.security.enabled: false

liquibase:
  url: jdbc:postgresql://localhost:5432/postgres?currentSchema=gateway
  default-schema: gateway
  user: postgres
  password: postgres

logging:
  level:
    root: WARN
    uk.gov.ons.fwmt: DEBUG
    org.springframework.security: ERROR
    org.springframework.web: ERROR
    org.hibernate: ERROR
    org.apache.commons.dbcp2: ERROR
  file: target/SpringErrors/spring.log
  pattern:
    console: "%d{yyyy-MMM-dd HH:mm:ss.SSS} %-5level [%thread] %logger{15} - %msg%n"
    file: "%d{yyyy-MMM-dd HH:mm:ss.SSS} %-5level [%thread] %logger{15} - %msg%n"

security.user:
  name: user
  password: password

totalmobile:
  username: "..."
  password: "..."
  url: "https://ons.totalmobile.co.uk"
  message-queue-service: "/Live/Services/TM/v20/Messaging/MessageQueueWs.asmx"