spring:
  application:
    name: fwmt-csv-uploader
  datasource:
    driverClassName: org.postgresql.Driver
    continue-on-error: true
    schema: classpath:/schema-cloud.sql

liquibase:
  user: ${cloud.services.postgresql.connection.username}
  password: ${cloud.services.postgresql.connection.password}
  default-schema:
  url: ${cloud.services.postgresql.connection.jdbcurl}
  changeLog: classpath:db/changelog/db.changelog-master.yaml

# The following data is sensitive and must not be shared
totalmobile:
  username: “...”
  password: “...”
spring.datasource:
  username: “...”
  password: “...”
security.user:
  name: “...”
  password: “...”

