server:
  port: 9091

project:
  basedir: ${basedir}

totalmobile:
  url: "https://ons.totalmobile.co.uk"
  message-queue-service: "/Live/Services/TM/v20/Messaging/MessageQueueWs.asmx"

spring.http.multipart:
  max-file-size: 12800MB
  max-request-size: 12800MB

spring.datasource:
  url: jdbc:postgresql://localhost/postgres?currentSchema=gateway
  driver-class-name: org.postgresql.Driver
  continue-on-error: true

management.endpoint.health.show-details: always
endpoints.health.sensitive: false
management.security.enabled: false

liquibase:
  url: jdbc:postgresql://localhost:5432/postgres?currentSchema=gateway

logging:
  level:
    root: WARN
    uk.gov.ons.fwmt: DEBUG
    org.springframework.security: ERROR
    org.springframework.web: ERROR
    org.hibernate: ERROR
    org.apache.commons.dbcp2: ERROR
  file: target/SpringErrors/spring.log
  pattern:
    console: "%d{yyyy-MMM-dd HH:mm:ss.SSS} %-5level [%thread] %logger{15} - %msg%n"
    file: "%d{yyyy-MMM-dd HH:mm:ss.SSS} %-5level [%thread] %logger{15} - %msg%n"

# The following data is sensitive and must not be shared
totalmobile:
  username: “...”
  password: “...”
spring.datasource:
  username: “...”
  password: “...”
security.user:
  name: “...”
  password: “...”