package uk.gov.ons.fwmt.gateway.utility.readers;

import com.opencsv.bean.CsvToBean;
import com.opencsv.bean.CsvToBeanBuilder;
import com.opencsv.bean.HeaderColumnNameMappingStrategy;
import lombok.AllArgsConstructor;
import lombok.Data;
import lombok.NoArgsConstructor;
import lombok.extern.slf4j.Slf4j;

import java.io.InputStream;
import java.io.InputStreamReader;
import java.util.Iterator;

@Slf4j
public class LegacySampleReader {
    private CsvToBean<LegacySampleEntityRaw> csvToBean;

    public LegacySampleReader(InputStream stream) {
        HeaderColumnNameMappingStrategy<LegacySampleEntityRaw> strategy = new HeaderColumnNameMappingStrategy<>();
        strategy.setType(LegacySampleEntityRaw.class);
        CsvToBeanBuilder<LegacySampleEntityRaw> builder = new CsvToBeanBuilder<>(new InputStreamReader(stream));
        csvToBean = builder
                .withMappingStrategy(strategy)
                .build();
    }

    public Iterator<LegacySampleEntityRaw> iterator() {
        return csvToBean.iterator();
    }

    @Data
    @AllArgsConstructor
    @NoArgsConstructor
    private class LegacySampleEntityRaw {
        private String serno;
        private String tla;
        private String fp;
        private String quotano;
        private String issueno;
        private String part;
        private String auth;
        private String employeeno;
        private String lastupdated;
        private String refdate;
        private String quota;
        private String week;
        private String w1yr;
        private String qrtr;
        private String addr;
        private String wavfnd;
        private String hhld;
        private String chklet;
        private String thiswv;
        private String prem1;
        private String prem2;
        private String prem3;
        private String prem4;
        private String district;
        private String posttown;
        private String postcode;
        private String divaddind;
        private String mo;
        private String direction;
        private String hout;
        private String lstho;
        private String lfssamp;
        private String thanks;
        private String thanke;
        private String teleno;
        private String reception;
        private String country;
        private String osgridref;
        private String main;
        private String numhhld;
        private String hhlddesc;
        private String numper;
        private String qreslinename1;
        private String qreslinename2;
        private String qreslinename3;
        private String qreslinename4;
        private String qreslinename5;
        private String qreslinename6;
        private String qreslinename7;
        private String qreslinename8;
        private String qreslinename9;
        private String qreslinename10;
        private String qreslinename11;
        private String qreslinename12;
        private String qreslinename13;
        private String qreslinename14;
        private String qreslinename15;
        private String qreslinename16;
        private String qreslineage1;
        private String qreslineage2;
        private String qreslineage3;
        private String qreslineage4;
        private String qreslineage5;
        private String qreslineage6;
        private String qreslineage7;
        private String qreslineage8;
        private String qreslineage9;
        private String qreslineage10;
        private String qreslineage11;
        private String qreslineage12;
        private String qreslineage13;
        private String qreslineage14;
        private String qreslineage15;
        private String qreslineage16;
        private String qindiv1wrking;
        private String qindiv1jbaway;
        private String qindiv1ownbus;
        private String qindiv1relbus;
        private String qindiv1look4;
        private String qindiv1difjob;
        private String qindiv1indout;
        private String qindiv2wrking;
        private String qindiv2jbaway;
        private String qindiv2ownbus;
        private String qindiv2relbus;
        private String qindiv2look4;
        private String qindiv2difjob;
        private String qindiv2indout;
        private String qindiv3wrking;
        private String qindiv3jbaway;
        private String qindiv3ownbus;
        private String qindiv3relbus;
        private String qindiv3look4;
        private String qindiv3difjob;
        private String qindiv3indout;
        private String qindiv4wrking;
        private String qindiv4jbaway;
        private String qindiv4ownbus;
        private String qindiv4relbus;
        private String qindiv4look4;
        private String qindiv4difjob;
        private String qindiv4indout;
        private String qindiv5wrking;
        private String qindiv5jbaway;
        private String qindiv5ownbus;
        private String qindiv5relbus;
        private String qindiv5look4;
        private String qindiv5difjob;
        private String qindiv5indout;
        private String qindiv6wrking;
        private String qindiv6jbaway;
        private String qindiv6ownbus;
        private String qindiv6relbus;
        private String qindiv6look4;
        private String qindiv6difjob;
        private String qindiv6indout;
        private String qindiv7wrking;
        private String qindiv7jbaway;
        private String qindiv7ownbus;
        private String qindiv7relbus;
        private String qindiv7look4;
        private String qindiv7difjob;
        private String qindiv7indout;
        private String qindiv8wrking;
        private String qindiv8jbaway;
        private String qindiv8ownbus;
        private String qindiv8relbus;
        private String qindiv8look4;
        private String qindiv8difjob;
        private String qindiv8indout;
        private String qindiv9wrking;
        private String qindiv9jbaway;
        private String qindiv9ownbus;
        private String qindiv9relbus;
        private String qindiv9look4;
        private String qindiv9difjob;
        private String qindiv9indout;
        private String qindiv10wrking;
        private String qindiv10jbaway;
        private String qindiv10ownbus;
        private String qindiv10relbus;
        private String qindiv10look4;
        private String qindiv10difjob;
        private String qindiv10indout;
        private String qindiv11wrking;
        private String qindiv11jbaway;
        private String qindiv11ownbus;
        private String qindiv11relbus;
        private String qindiv11look4;
        private String qindiv11difjob;
        private String qindiv11indout;
        private String qindiv12wrking;
        private String qindiv12jbaway;
        private String qindiv12ownbus;
        private String qindiv12relbus;
        private String qindiv12look4;
        private String qindiv12difjob;
        private String qindiv12indout;
        private String qindiv13wrking;
        private String qindiv13jbaway;
        private String qindiv13ownbus;
        private String qindiv13relbus;
        private String qindiv13look4;
        private String qindiv13difjob;
        private String qindiv13indout;
        private String qindiv14wrking;
        private String qindiv14jbaway;
        private String qindiv14ownbus;
        private String qindiv14relbus;
        private String qindiv14look4;
        private String qindiv14difjob;
        private String qindiv14indout;
        private String qindiv15wrking;
        private String qindiv15jbaway;
        private String qindiv15ownbus;
        private String qindiv15relbus;
        private String qindiv15look4;
        private String qindiv15difjob;
        private String qindiv15indout;
        private String qindiv16wrking;
        private String qindiv16jbaway;
        private String qindiv16ownbus;
        private String qindiv16relbus;
        private String qindiv16look4;
        private String qindiv16difjob;
        private String qindiv16indout;
        private String intvno;
        private String briefsdc1;
        private String briefsdc2;
        private String briefsdc3;
        private String brief1;
    }
}
