package uk.gov.ons.fwmt.gateway.utility.readers;

import com.opencsv.bean.ColumnPositionMappingStrategy;
import com.opencsv.bean.CsvToBean;
import com.opencsv.bean.CsvToBeanBuilder;
import com.opencsv.bean.HeaderColumnNameTranslateMappingStrategy;
import lombok.Data;
import lombok.NoArgsConstructor;
import lombok.extern.slf4j.Slf4j;
import uk.gov.ons.fwmt.gateway.entity.LegacySampleEntity;

import java.io.InputStream;
import java.io.InputStreamReader;
import java.util.HashMap;
import java.util.Iterator;
import java.util.Map;

@Slf4j
public class LegacyLFSSampleReader {
  private static final Map<String, String> SAMPLE_LFS_DATA_COLUMN_MAP;

  static {
    Map<String, String> map = new HashMap<>();
    map.put("Expr1", "serno");
    map.put("TLA", "tla");
    map.put("FP", "fp");
    map.put("Quota_No", "quotano");
    map.put("Issue_No", "issueno");
    map.put("Part", "part");
    map.put("Auth", "auth");
    map.put("EmployeeNo", "employeeno");
    map.put("Last_Updated", "lastupdated");
    map.put("REFDATE", "refdate");
    map.put("QUOTA", "quota");
    map.put("WEEK", "week");
    map.put("W1YR", "w1yr");
    map.put("QRTR", "qrtr");
    map.put("ADDR", "addr");
    map.put("WAVFND", "wavfnd");
    map.put("HHLD", "hhld");
    map.put("CHKLET", "chklet");
    map.put("THISWV", "thiswv");
    map.put("PREM1", "prem1");
    map.put("PREM2", "prem2");
    map.put("PREM3", "prem3");
    map.put("PREM4", "prem4");
    map.put("DISTRICT", "district");
    map.put("POSTTOWN", "posttown");
    map.put("POSTCODE", "postcode");
    map.put("DIVADDIND", "divaddind");
    map.put("MO", "mo");
    map.put("DIRECTION", "direction");
    map.put("HOUT", "hout");
    map.put("LSTHO", "lstho");
    map.put("LFSSAMP", "lfssamp");
    map.put("THANKS", "thanks");
    map.put("THANKE", "thanke");
    map.put("TELENO", "teleno");
    map.put("RECEPTION", "reception");
    map.put("COUNTRY", "country");
    map.put("OSGRIDREF", "osgridref");
    map.put("MAIN", "main");
    map.put("NUMHHLD", "numhhld");
    map.put("HHLDDESC", "hhlddesc");
    map.put("NUMPER", "numper");
    map.put("QRES_LINE_NAME_1", "qresLineName1");
    map.put("QRES_LINE_NAME_2", "qresLineName2");
    map.put("QRES_LINE_NAME_3", "qresLineName3");
    map.put("QRES_LINE_NAME_4", "qresLineName4");
    map.put("QRES_LINE_NAME_5", "qresLineName5");
    map.put("QRES_LINE_NAME_6", "qresLineName6");
    map.put("QRES_LINE_NAME_7", "qresLineName7");
    map.put("QRES_LINE_NAME_8", "qresLineName8");
    map.put("QRES_LINE_NAME_9", "qresLineName9");
    map.put("QRES_LINE_NAME_10", "qresLineName10");
    map.put("QRES_LINE_NAME_11", "qresLineName11");
    map.put("QRES_LINE_NAME_12", "qresLineName12");
    map.put("QRES_LINE_NAME_13", "qresLineName13");
    map.put("QRES_LINE_NAME_14", "qresLineName14");
    map.put("QRES_LINE_NAME_15", "qresLineName15");
    map.put("QRES_LINE_NAME_16", "qresLineName16");
    map.put("QRES_LINE_AGE_1", "qresLineAge1");
    map.put("QRES_LINE_AGE_2", "qresLineAge2");
    map.put("QRES_LINE_AGE_3", "qresLineAge3");
    map.put("QRES_LINE_AGE_4", "qresLineAge4");
    map.put("QRES_LINE_AGE_5", "qresLineAge5");
    map.put("QRES_LINE_AGE_6", "qresLineAge6");
    map.put("QRES_LINE_AGE_7", "qresLineAge7");
    map.put("QRES_LINE_AGE_8", "qresLineAge8");
    map.put("QRES_LINE_AGE_9", "qresLineAge9");
    map.put("QRES_LINE_AGE_10", "qresLineAge10");
    map.put("QRES_LINE_AGE_11", "qresLineAge11");
    map.put("QRES_LINE_AGE_12", "qresLineAge12");
    map.put("QRES_LINE_AGE_13", "qresLineAge13");
    map.put("QRES_LINE_AGE_14", "qresLineAge14");
    map.put("QRES_LINE_AGE_15", "qresLineAge15");
    map.put("QRES_LINE_AGE_16", "qresLineAge16");
    map.put("QINDIV_1_WRKING", "qindiv1Wrking");
    map.put("QINDIV_1_JBAWAY", "qindiv1Jbaway");
    map.put("QINDIV_1_OWNBUS", "qindiv1Ownbus");
    map.put("QINDIV_1_RELBUS", "qindiv1Relbus");
    map.put("QINDIV_1_LOOK4", "qindiv1Look4");
    map.put("QINDIV_1_DIFJOB", "qindiv1Difjob");
    map.put("QINDIV_1_INDOUT", "qindiv1Indout");
    map.put("QINDIV_2_WRKING", "qindiv2Wrking");
    map.put("QINDIV_2_JBAWAY", "qindiv2Jbaway");
    map.put("QINDIV_2_OWNBUS", "qindiv2Ownbus");
    map.put("QINDIV_2_RELBUS", "qindiv2Relbus");
    map.put("QINDIV_2_LOOK4", "qindiv2Look4");
    map.put("QINDIV_2_DIFJOB", "qindiv2Difjob");
    map.put("QINDIV_2_INDOUT", "qindiv2Indout");
    map.put("QINDIV_3_WRKING", "qindiv3Wrking");
    map.put("QINDIV_3_JBAWAY", "qindiv3Jbaway");
    map.put("QINDIV_3_OWNBUS", "qindiv3Ownbus");
    map.put("QINDIV_3_RELBUS", "qindiv3Relbus");
    map.put("QINDIV_3_LOOK4", "qindiv3Look4");
    map.put("QINDIV_3_DIFJOB", "qindiv3Difjob");
    map.put("QINDIV_3_INDOUT", "qindiv3Indout");
    map.put("QINDIV_4_WRKING", "qindiv4Wrking");
    map.put("QINDIV_4_JBAWAY", "qindiv4Jbaway");
    map.put("QINDIV_4_OWNBUS", "qindiv4Ownbus");
    map.put("QINDIV_4_RELBUS", "qindiv4Relbus");
    map.put("QINDIV_4_LOOK4", "qindiv4Look4");
    map.put("QINDIV_4_DIFJOB", "qindiv4Difjob");
    map.put("QINDIV_4_INDOUT", "qindiv4Indout");
    map.put("QINDIV_5_WRKING", "qindiv5Wrking");
    map.put("QINDIV_5_JBAWAY", "qindiv5Jbaway");
    map.put("QINDIV_5_OWNBUS", "qindiv5Ownbus");
    map.put("QINDIV_5_RELBUS", "qindiv5Relbus");
    map.put("QINDIV_5_LOOK4", "qindiv5Look4");
    map.put("QINDIV_5_DIFJOB", "qindiv5Difjob");
    map.put("QINDIV_5_INDOUT", "qindiv5Indout");
    map.put("QINDIV_6_WRKING", "qindiv6Wrking");
    map.put("QINDIV_6_JBAWAY", "qindiv6Jbaway");
    map.put("QINDIV_6_OWNBUS", "qindiv6Ownbus");
    map.put("QINDIV_6_RELBUS", "qindiv6Relbus");
    map.put("QINDIV_6_LOOK4", "qindiv6Look4");
    map.put("QINDIV_6_DIFJOB", "qindiv6Difjob");
    map.put("QINDIV_6_INDOUT", "qindiv6Indout");
    map.put("QINDIV_7_WRKING", "qindiv7Wrking");
    map.put("QINDIV_7_JBAWAY", "qindiv7Jbaway");
    map.put("QINDIV_7_OWNBUS", "qindiv7Ownbus");
    map.put("QINDIV_7_RELBUS", "qindiv7Relbus");
    map.put("QINDIV_7_LOOK4", "qindiv7Look4");
    map.put("QINDIV_7_DIFJOB", "qindiv7Difjob");
    map.put("QINDIV_7_INDOUT", "qindiv7Indout");
    map.put("QINDIV_8_WRKING", "qindiv8Wrking");
    map.put("QINDIV_8_JBAWAY", "qindiv8Jbaway");
    map.put("QINDIV_8_OWNBUS", "qindiv8Ownbus");
    map.put("QINDIV_8_RELBUS", "qindiv8Relbus");
    map.put("QINDIV_8_LOOK4", "qindiv8Look4");
    map.put("QINDIV_8_DIFJOB", "qindiv8Difjob");
    map.put("QINDIV_8_INDOUT", "qindiv8Indout");
    map.put("QINDIV_9_WRKING", "qindiv9Wrking");
    map.put("QINDIV_9_JBAWAY", "qindiv9Jbaway");
    map.put("QINDIV_9_OWNBUS", "qindiv9Ownbus");
    map.put("QINDIV_9_RELBUS", "qindiv9Relbus");
    map.put("QINDIV_9_LOOK4", "qindiv9Look4");
    map.put("QINDIV_9_DIFJOB", "qindiv9Difjob");
    map.put("QINDIV_9_INDOUT", "qindiv9Indout");
    map.put("QINDIV_10_WRKING", "qindiv10Wrking");
    map.put("QINDIV_10_JBAWAY", "qindiv10Jbaway");
    map.put("QINDIV_10_OWNBUS", "qindiv10Ownbus");
    map.put("QINDIV_10_RELBUS", "qindiv10Relbus");
    map.put("QINDIV_10_LOOK4", "qindiv10Look4");
    map.put("QINDIV_10_DIFJOB", "qindiv10Difjob");
    map.put("QINDIV_10_INDOUT", "qindiv10Indout");
    map.put("QINDIV_11_WRKING", "qindiv11Wrking");
    map.put("QINDIV_11_JBAWAY", "qindiv11Jbaway");
    map.put("QINDIV_11_OWNBUS", "qindiv11Ownbus");
    map.put("QINDIV_11_RELBUS", "qindiv11Relbus");
    map.put("QINDIV_11_LOOK4", "qindiv11Look4");
    map.put("QINDIV_11_DIFJOB", "qindiv11Difjob");
    map.put("QINDIV_11_INDOUT", "qindiv11Indout");
    map.put("QINDIV_12_WRKING", "qindiv12Wrking");
    map.put("QINDIV_12_JBAWAY", "qindiv12Jbaway");
    map.put("QINDIV_12_OWNBUS", "qindiv12Ownbus");
    map.put("QINDIV_12_RELBUS", "qindiv12Relbus");
    map.put("QINDIV_12_LOOK4", "qindiv12Look4");
    map.put("QINDIV_12_DIFJOB", "qindiv12Difjob");
    map.put("QINDIV_12_INDOUT", "qindiv12Indout");
    map.put("QINDIV_13_WRKING", "qindiv13Wrking");
    map.put("QINDIV_13_JBAWAY", "qindiv13Jbaway");
    map.put("QINDIV_13_OWNBUS", "qindiv13Ownbus");
    map.put("QINDIV_13_RELBUS", "qindiv13Relbus");
    map.put("QINDIV_13_LOOK4", "qindiv13Look4");
    map.put("QINDIV_13_DIFJOB", "qindiv13Difjob");
    map.put("QINDIV_13_INDOUT", "qindiv13Indout");
    map.put("QINDIV_14_WRKING", "qindiv14Wrking");
    map.put("QINDIV_14_JBAWAY", "qindiv14Jbaway");
    map.put("QINDIV_14_OWNBUS", "qindiv14Ownbus");
    map.put("QINDIV_14_RELBUS", "qindiv14Relbus");
    map.put("QINDIV_14_LOOK4", "qindiv14Look4");
    map.put("QINDIV_14_DIFJOB", "qindiv14Difjob");
    map.put("QINDIV_14_INDOUT", "qindiv14Indout");
    map.put("QINDIV_15_WRKING", "qindiv15Wrking");
    map.put("QINDIV_15_JBAWAY", "qindiv15Jbaway");
    map.put("QINDIV_15_OWNBUS", "qindiv15Ownbus");
    map.put("QINDIV_15_RELBUS", "qindiv15Relbus");
    map.put("QINDIV_15_LOOK4", "qindiv15Look4");
    map.put("QINDIV_15_DIFJOB", "qindiv15Difjob");
    map.put("QINDIV_15_INDOUT", "qindiv15Indout");
    map.put("QINDIV_16_WRKING", "qindiv16Wrking");
    map.put("QINDIV_16_JBAWAY", "qindiv16Jbaway");
    map.put("QINDIV_16_OWNBUS", "qindiv16Ownbus");
    map.put("QINDIV_16_RELBUS", "qindiv16Relbus");
    map.put("QINDIV_16_LOOK4", "qindiv16Look4");
    map.put("QINDIV_16_DIFJOB", "qindiv16Difjob");
    map.put("QINDIV_16_INDOUT", "qindiv16Indout");
    map.put("COMMENT_1_REFDTE", "comment1Refdte");
    map.put("COMMENT_1_INTVNO", "comment1Intvno");
    map.put("COMMENT_1_BriefSDC1", "comment1BriefSDC1");
    map.put("COMMENT_1_BriefSDC2", "comment1BriefSDC2");
    map.put("COMMENT_1_BriefSDC3", "comment1BriefSDC3");
    map.put("COMMENT_1_BRIEF1", "comment1Brief1");
    map.put("COMMENT_2_REFDTE", "comment2Refdte");
    map.put("COMMENT_2_INTVNO", "comment2Intvno");
    map.put("COMMENT_2_BriefSDC1", "comment2BriefSDC1");
    map.put("COMMENT_2_BriefSDC2", "comment2BriefSDC2");
    map.put("COMMENT_2_BriefSDC3", "comment2BriefSDC3");
    map.put("COMMENT_2_BRIEF1", "comment2Brief1");
    map.put("COMMENT_3_REFDTE", "comment3Refdte");
    map.put("COMMENT_3_INTVNO", "comment3Intvno");
    map.put("COMMENT_3_BriefSDC1", "comment3BriefSDC1");
    map.put("COMMENT_3_BriefSDC2", "comment3BriefSDC2");
    map.put("COMMENT_3_BriefSDC3", "comment3BriefSDC3");
    map.put("COMMENT_3_BRIEF1", "comment3Brief1");
    map.put("COMMENT_4_REFDTE", "comment4Refdte");
    map.put("COMMENT_4_INTVNO", "comment4Intvno");
    map.put("COMMENT_4_BriefSDC1", "comment4BriefSDC1");
    map.put("COMMENT_4_BriefSDC2", "comment4BriefSDC2");
    map.put("COMMENT_4_BriefSDC3", "comment4BriefSDC3");
    map.put("COMMENT_4_BRIEF1", "comment4Brief1");
    map.put("COMMENT_5_REFDTE", "comment5Refdte");
    map.put("COMMENT_5_INTVNO", "comment5Intvno");
    map.put("COMMENT_5_BriefSDC1", "comment5BriefSDC1");
    map.put("COMMENT_5_BriefSDC2", "comment5BriefSDC2");
    map.put("COMMENT_5_BriefSDC3", "comment5BriefSDC3");
    map.put("COMMENT_5_BRIEF1", "comment5Brief1");
    SAMPLE_LFS_DATA_COLUMN_MAP = map;
  }

  private CsvToBean<LegacyLFSSampleEntityRaw> csvToBean;

  public LegacyLFSSampleReader(InputStream stream) {
    HeaderColumnNameTranslateMappingStrategy<LegacyLFSSampleEntityRaw> strategy =
        new HeaderColumnNameTranslateMappingStrategy<>();
    strategy.setType(LegacyLFSSampleEntityRaw.class);
    strategy.setColumnMapping(SAMPLE_LFS_DATA_COLUMN_MAP);
    CsvToBeanBuilder<LegacyLFSSampleEntityRaw> builder = new CsvToBeanBuilder<>(new InputStreamReader(stream));
    csvToBean = builder
        .withMappingStrategy(strategy)
        .build();
  }

  public Iterator<LegacySampleEntity> iterator() {
    return new LegacyLFSSampleIterator(csvToBean.iterator());
  }

  /// This iterator strips excess data out of the LegacyLFSSampleEntityRaw structure as it iterates
  private class LegacyLFSSampleIterator implements Iterator<LegacySampleEntity> {
    Iterator<LegacyLFSSampleEntityRaw> rawIterator;

    LegacyLFSSampleIterator(Iterator<LegacyLFSSampleEntityRaw> rawIter) {
      this.rawIterator = rawIter;
    }

    @Override public boolean hasNext() {
      return rawIterator.hasNext();
    }

    @Override public LegacySampleEntity next() {
      LegacyLFSSampleEntityRaw raw = rawIterator.next();
      if (raw == null) {
        return null;
      }
      LegacySampleEntity entity = new LegacySampleEntity();
      // TODO add fields
      return entity;
    }
  }

  @Data
  @NoArgsConstructor
  private class LegacyLFSSampleEntityRaw {
    private String serno;
    private String tla;
    private String fp;
    private String quotano;
    private String issueno;
    private String part;
    private String auth;
    private String employeeno;
    private String lastupdated;
    private String refdate;
    private String quota;
    private String week;
    private String w1yr;
    private String qrtr;
    private String addr;
    private String wavfnd;
    private String hhld;
    private String chklet;
    private String thiswv;
    private String prem1;
    private String prem2;
    private String prem3;
    private String prem4;
    private String district;
    private String posttown;
    private String postcode;
    private String divaddind;
    private String mo;
    private String direction;
    private String hout;
    private String lstho;
    private String lfssamp;
    private String thanks;
    private String thanke;
    private String teleno;
    private String reception;
    private String country;
    private String osgridref;
    private String main;
    private String numhhld;
    private String hhlddesc;
    private String numper;
    private String qresLineName1;
    private String qresLineName2;
    private String qresLineName3;
    private String qresLineName4;
    private String qresLineName5;
    private String qresLineName6;
    private String qresLineName7;
    private String qresLineName8;
    private String qresLineName9;
    private String qresLineName10;
    private String qresLineName11;
    private String qresLineName12;
    private String qresLineName13;
    private String qresLineName14;
    private String qresLineName15;
    private String qresLineName16;
    private String qresLineAge1;
    private String qresLineAge2;
    private String qresLineAge3;
    private String qresLineAge4;
    private String qresLineAge5;
    private String qresLineAge6;
    private String qresLineAge7;
    private String qresLineAge8;
    private String qresLineAge9;
    private String qresLineAge10;
    private String qresLineAge11;
    private String qresLineAge12;
    private String qresLineAge13;
    private String qresLineAge14;
    private String qresLineAge15;
    private String qresLineAge16;
    private String qindiv1Wrking;
    private String qindiv1Jbaway;
    private String qindiv1Ownbus;
    private String qindiv1Relbus;
    private String qindiv1Look4;
    private String qindiv1Difjob;
    private String qindiv1Indout;
    private String qindiv2Wrking;
    private String qindiv2Jbaway;
    private String qindiv2Ownbus;
    private String qindiv2Relbus;
    private String qindiv2Look4;
    private String qindiv2Difjob;
    private String qindiv2Indout;
    private String qindiv3Wrking;
    private String qindiv3Jbaway;
    private String qindiv3Ownbus;
    private String qindiv3Relbus;
    private String qindiv3Look4;
    private String qindiv3Difjob;
    private String qindiv3Indout;
    private String qindiv4Wrking;
    private String qindiv4Jbaway;
    private String qindiv4Ownbus;
    private String qindiv4Relbus;
    private String qindiv4Look4;
    private String qindiv4Difjob;
    private String qindiv4Indout;
    private String qindiv5Wrking;
    private String qindiv5Jbaway;
    private String qindiv5Ownbus;
    private String qindiv5Relbus;
    private String qindiv5Look4;
    private String qindiv5Difjob;
    private String qindiv5Indout;
    private String qindiv6Wrking;
    private String qindiv6Jbaway;
    private String qindiv6Ownbus;
    private String qindiv6Relbus;
    private String qindiv6Look4;
    private String qindiv6Difjob;
    private String qindiv6Indout;
    private String qindiv7Wrking;
    private String qindiv7Jbaway;
    private String qindiv7Ownbus;
    private String qindiv7Relbus;
    private String qindiv7Look4;
    private String qindiv7Difjob;
    private String qindiv7Indout;
    private String qindiv8Wrking;
    private String qindiv8Jbaway;
    private String qindiv8Ownbus;
    private String qindiv8Relbus;
    private String qindiv8Look4;
    private String qindiv8Difjob;
    private String qindiv8Indout;
    private String qindiv9Wrking;
    private String qindiv9Jbaway;
    private String qindiv9Ownbus;
    private String qindiv9Relbus;
    private String qindiv9Look4;
    private String qindiv9Difjob;
    private String qindiv9Indout;
    private String qindiv10Wrking;
    private String qindiv10Jbaway;
    private String qindiv10Ownbus;
    private String qindiv10Relbus;
    private String qindiv10Look4;
    private String qindiv10Difjob;
    private String qindiv10Indout;
    private String qindiv11Wrking;
    private String qindiv11Jbaway;
    private String qindiv11Ownbus;
    private String qindiv11Relbus;
    private String qindiv11Look4;
    private String qindiv11Difjob;
    private String qindiv11Indout;
    private String qindiv12Wrking;
    private String qindiv12Jbaway;
    private String qindiv12Ownbus;
    private String qindiv12Relbus;
    private String qindiv12Look4;
    private String qindiv12Difjob;
    private String qindiv12Indout;
    private String qindiv13Wrking;
    private String qindiv13Jbaway;
    private String qindiv13Ownbus;
    private String qindiv13Relbus;
    private String qindiv13Look4;
    private String qindiv13Difjob;
    private String qindiv13Indout;
    private String qindiv14Wrking;
    private String qindiv14Jbaway;
    private String qindiv14Ownbus;
    private String qindiv14Relbus;
    private String qindiv14Look4;
    private String qindiv14Difjob;
    private String qindiv14Indout;
    private String qindiv15Wrking;
    private String qindiv15Jbaway;
    private String qindiv15Ownbus;
    private String qindiv15Relbus;
    private String qindiv15Look4;
    private String qindiv15Difjob;
    private String qindiv15Indout;
    private String qindiv16Wrking;
    private String qindiv16Jbaway;
    private String qindiv16Ownbus;
    private String qindiv16Relbus;
    private String qindiv16Look4;
    private String qindiv16Difjob;
    private String qindiv16Indout;
    private String comment1Refdte;
    private String comment1Intvno;
    private String comment1BriefSDC1;
    private String comment1BriefSDC2;
    private String comment1BriefSDC3;
    private String comment1Brief1;
    private String comment2Refdte;
    private String comment2Intvno;
    private String comment2BriefSDC1;
    private String comment2BriefSDC2;
    private String comment2BriefSDC3;
    private String comment2Brief1;
    private String comment3Refdte;
    private String comment3Intvno;
    private String comment3BriefSDC1;
    private String comment3BriefSDC2;
    private String comment3BriefSDC3;
    private String comment3Brief1;
    private String comment4Refdte;
    private String comment4Intvno;
    private String comment4BriefSDC1;
    private String comment4BriefSDC2;
    private String comment4BriefSDC3;
    private String comment4Brief1;
    private String comment5Refdte;
    private String comment5Intvno;
    private String comment5BriefSDC1;
    private String comment5BriefSDC2;
    private String comment5BriefSDC3;
    private String comment5Brief1;
  }
}
