DO $$
BEGIN
IF EXISTS (SELECT 1 FROM pg_roles WHERE rolname='gatewayrole') THEN
   REVOKE ALL PRIVILEGES ON DATABASE postgres FROM gatewayrole;
END IF;
END$$;

DROP SCHEMA IF EXISTS gateway CASCADE;
DROP ROLE IF EXISTS gatewayrole;

CREATE ROLE gatewayrole PASSWORD 'gatewayrole' NOSUPERUSER NOCREATEDB NOCREATEROLE NOREPLICATION INHERIT LOGIN;

CREATE SCHEMA gateway AUTHORIZATION gatewayrole;

REVOKE ALL ON ALL TABLES IN SCHEMA gateway FROM PUBLIC;
REVOKE ALL ON ALL SEQUENCES IN SCHEMA gateway FROM PUBLIC;
REVOKE CONNECT ON DATABASE postgres FROM PUBLIC;

GRANT CONNECT ON DATABASE postgres TO gatewayrole;
GRANT SELECT, INSERT, UPDATE, DELETE ON ALL TABLES IN SCHEMA gateway TO gatewayrole;
GRANT ALL ON ALL SEQUENCES IN SCHEMA gateway TO gatewayrole;
