SET SCHEMA 'gateway';

CREATE TABLE gateway.staff
 (
    employeeNo        CHARACTER VARYING(255) PRIMARY KEY,
    authNo            CHARACTER VARYING(255) UNIQUE,
    title             CHARACTER VARYING(255),
    firstname         CHARACTER VARYING(255),
    surname           CHARACTER VARYING(255),
    sex               CHARACTER VARYING(255),
    address1          CHARACTER VARYING(255),
    address2          CHARACTER VARYING(255),
    address3          CHARACTER VARYING(255),
    address4          CHARACTER VARYING(255),
    postcode          CHARACTER VARYING(255),
    tel               CHARACTER VARYING(255),
    tel2              CHARACTER VARYING(255),
    mobileTel         CHARACTER VARYING(255),
    emergencyTel      CHARACTER VARYING(255),
    email             CHARACTER VARYING(255),
    gor               CHARACTER VARYING(255),
    county            CHARACTER VARYING(255),
    gridRef           CHARACTER VARYING(255),
    mainFieldForce    CHARACTER VARYING(255),
    dateOfBirth       CHARACTER VARYING(255),
    inactiveNo        CHARACTER VARYING(255),
    easting           CHARACTER VARYING(255),
    northing          CHARACTER VARYING(255),
    fieldManager      CHARACTER VARYING(255),
    managerEmployeeNo CHARACTER VARYING(255),
    managerAuth       CHARACTER VARYING(255),
    managerFirstname  CHARACTER VARYING(255),
    managerSurname    CHARACTER VARYING(255),
    region            CHARACTER VARYING(255),
    regionName        CHARACTER VARYING(255),
    rmEmployeeNo      CHARACTER VARYING(255),
    rmFirstname       CHARACTER VARYING(255),
    rmSurname         CHARACTER VARYING(255)
 );
